export type StatCategory = 'preflop' | 'postflop' | 'showdown'

export interface StatDefinition {
  id: string
  label: string
  /** Longest aliases first so e.g. "Fold to 3Bet" wins over "3Bet". */
  aliases: string[]
  category: StatCategory
  unit: '%' | 'bb100'
  /** Fallback range when no position target exists (e.g. winrate). */
  range: [number, number]
  lowAdvice: string
  highAdvice: string
}

/** PT4/HM export columns used for leak analysis (percentage stats only; Count/Hands columns are ignored). */
export const STAT_DEFINITIONS: StatDefinition[] = [
  {
    id: 'allInAdjBb100',
    label: 'All-In Adj BB/100',
    aliases: ['All-In Adj BB/100', 'All In Adj BB/100'],
    category: 'showdown',
    unit: 'bb100',
    range: [-3, 4],
    lowAdvice: 'Winrate is below break-even. Review your biggest leaks before moving up.',
    highAdvice: 'Strong winrate — make sure you are not running above EV; keep studying spots that still cost you bb/100.',
  },
  {
    id: 'raiseFirst',
    label: 'Raise First',
    aliases: ['Raise First In', 'Raise First', 'RFI', 'UOPFR'],
    category: 'preflop',
    unit: '%',
    range: [15, 22],
    lowAdvice: 'You open too few pots when folded to you. Raise first-in more, especially from late position.',
    highAdvice: 'You open very wide when folded to you. Trim the weakest opens from early and middle position.',
  },
  {
    id: 'limpOpen',
    label: 'Limp Open',
    aliases: ['Limp Open', 'Limp Open Raise'],
    category: 'preflop',
    unit: '%',
    range: [0, 1.5],
    lowAdvice: 'Very tight limping — fine if you are not limping at all.',
    highAdvice: 'You limp open too often. Default to raising; limping invites multiway pots and loses initiative.',
  },
  {
    id: 'limpRaise',
    label: 'Limp/Raise',
    aliases: ['Limp/Raise', 'Limp Raise'],
    category: 'preflop',
    unit: '%',
    range: [0, 1.5],
    lowAdvice: 'Low limp-raise frequency is normal unless you use it as a deliberate strategy.',
    highAdvice: 'You limp-raise too often. This line is easily exploited — tighten your limp-raise range.',
  },
  {
    id: 'limpCall',
    label: 'Limp/Call',
    aliases: ['Limp/Call', 'Limp Call'],
    category: 'preflop',
    unit: '%',
    range: [0, 3],
    lowAdvice: 'Low limp-call frequency is fine.',
    highAdvice: 'You limp-call too much. Either raise your limps or fold dominated hands to raises.',
  },
  {
    id: 'limpFold',
    label: 'Limp/Fold',
    aliases: ['Limp/Fold', 'Limp Fold'],
    category: 'preflop',
    unit: '%',
    range: [0, 8],
    lowAdvice: 'Low limp-fold is normal.',
    highAdvice: 'You limp and fold too often — dead money. Stop limping weak hands you will not defend.',
  },
  {
    id: 'raiseSbOpenLimp',
    label: 'Raise SB Open Limp',
    aliases: ['Raise SB Open Limp', 'SB Open Limp Raise'],
    category: 'preflop',
    unit: '%',
    range: [25, 42],
    lowAdvice: 'You complete the SB too often vs limpers. Raise more to isolate weak limps.',
    highAdvice: 'You raise every limp from the SB. Mix in some completes with playable hands.',
  },
  {
    id: 'foldBbVsSb',
    label: 'Fold BB v SB',
    aliases: ['Fold BB v SB', 'Fold BB vs SB', 'BB Fold vs SB'],
    category: 'preflop',
    unit: '%',
    range: [42, 58],
    lowAdvice: 'You defend too wide vs SB opens. Fold more offsuit junk.',
    highAdvice: 'You fold too much vs SB opens. Defend more suited hands and broadways.',
  },
  {
    id: 'foldToSteal',
    label: 'Fold to Steal',
    aliases: ['Fold BB to Steal', 'BB Fold to Steal', 'Fold to Steal'],
    category: 'preflop',
    unit: '%',
    range: [60, 76],
    lowAdvice: 'You defend the big blind too wide vs steals. Fold more junk offsuit hands.',
    highAdvice: 'You surrender your big blind too often. Defend more suited hands and broadways vs late opens.',
  },
  {
    id: 'callPf2Bet',
    label: 'Call PF 2Bet',
    aliases: ['Call PF 2Bet', 'Call Preflop 2Bet', 'Call 2Bet PF'],
    category: 'preflop',
    unit: '%',
    range: [6, 13],
    lowAdvice: 'You flat too few opens. Add some suited connectors and pairs in position.',
    highAdvice: 'You flat opens too often. 3-bet or fold more — avoid calling dominated offsuit hands.',
  },
  {
    id: 'threeBetPf',
    label: '3Bet PF',
    aliases: ['3Bet PF', '3-Bet PF', '3-Bet Preflop', '3Bet', '3-Bet'],
    category: 'preflop',
    unit: '%',
    range: [4.5, 8.5],
    lowAdvice: 'You 3-bet too little. Add light 3-bets vs late-position opens instead of flatting.',
    highAdvice: 'You 3-bet very aggressively. Ensure your range is not too bluff-heavy out of position.',
  },
  {
    id: 'threeBetSteal',
    label: '3Bet Steal',
    aliases: ['3Bet Steal', '3-Bet Steal'],
    category: 'preflop',
    unit: '%',
    range: [6, 14],
    lowAdvice: 'You rarely 3-bet vs steals. Add light 3-bets from the blinds vs wide late opens.',
    highAdvice: 'You 3-bet steals very often. Balance with more calls or you become easy to 4-bet.',
  },
  {
    id: 'threeBetNaiLt35',
    label: '3Bet NAI <35',
    aliases: ['3Bet NAI <35', '3Bet NAI < 35', '3-Bet NAI <35'],
    category: 'preflop',
    unit: '%',
    range: [3.5, 7],
    lowAdvice: 'Low non-all-in 3-bet frequency — add more small 3-bets in position.',
    highAdvice: 'Very high non-all-in 3-bet rate. Make sure sizing and ranges are balanced.',
  },
  {
    id: 'twoBetPfAndFold',
    label: '2Bet PF & Fold',
    aliases: ['2Bet PF & Fold', '2-Bet PF & Fold', 'Fold to 3Bet', 'Fold to 3-Bet'],
    category: 'preflop',
    unit: '%',
    range: [52, 68],
    lowAdvice: 'You defend too many opens vs 3-bets. Fold more dominated hands (KJo, ATo).',
    highAdvice: 'You fold too much after opening — exploitable. Continue with suited hands and 4-bet bluff occasionally.',
  },
  {
    id: 'raiseAnd4BetPlusPf',
    label: 'Raise & 4Bet+ PF',
    aliases: ['Raise & 4Bet+ PF', 'Raise & 4Bet+ PF ', '4Bet PF', '4-Bet PF'],
    category: 'preflop',
    unit: '%',
    range: [1.5, 4],
    lowAdvice: 'You almost never 4-bet. Add value 4-bets with QQ+/AK and some A5s bluffs.',
    highAdvice: 'You 4-bet very often. Make sure you are not stacking off light preflop.',
  },
  {
    id: 'threeBetPfAndFold',
    label: '3Bet PF & Fold',
    aliases: ['3Bet PF & Fold', '3-Bet PF & Fold'],
    category: 'preflop',
    unit: '%',
    range: [52, 72],
    lowAdvice: 'You fold too few 3-bets vs 4-bets — stacking off light.',
    highAdvice: 'You fold too many 3-bets vs 4-bets. Continue with strong hands and add 5-bet bluffs.',
  },
  {
    id: 'foldToPf4BetAfter3BetLt30',
    label: 'Fold to PF 4Bet <30',
    aliases: [
      'Fold to PF 4Bet After 3Bet <30',
      'Fold to PF 4Bet After 3Bet <30 ',
      'Fold to 4Bet After 3Bet',
    ],
    category: 'preflop',
    unit: '%',
    range: [54, 70],
    lowAdvice: 'You call 4-bets too wide after 3-betting. Fold more bluff-catchers.',
    highAdvice: 'You fold too much to 4-bets after 3-betting — opponents can 4-bet you light.',
  },
  {
    id: 'pfSqueeze',
    label: 'PF Squeeze',
    aliases: ['PF Squeeze', 'Preflop Squeeze', 'Squeeze'],
    category: 'preflop',
    unit: '%',
    range: [4, 10],
    lowAdvice: 'You squeeze too rarely. Add squeezes with strong hands and suited blockers vs limp-calls.',
    highAdvice: 'You squeeze very often. Tighten your squeeze range out of position.',
  },
  {
    id: 'cbetFOopHu',
    label: 'CBet F OOP (HU)',
    aliases: ['CBet F OOP (HU)', 'C-Bet F OOP HU'],
    category: 'postflop',
    unit: '%',
    range: [32, 48],
    lowAdvice: 'You c-bet too little out of position heads-up. Bet more on boards that favor your range.',
    highAdvice: 'You c-bet too often OOP. Check more on low, connected boards that favor the caller.',
  },
  {
    id: 'cbetFIpHu',
    label: 'CBet F IP (HU)',
    aliases: ['CBet F IP (HU)', 'C-Bet F IP HU'],
    category: 'postflop',
    unit: '%',
    range: [52, 68],
    lowAdvice: 'You c-bet too little in position. Leverage position with more flop bets on favorable boards.',
    highAdvice: 'You c-bet too often IP. Check back more on boards that hit the caller range.',
  },
  {
    id: 'floatFHu',
    label: 'Float F HU',
    aliases: ['Float F HU', 'Float Flop HU'],
    category: 'postflop',
    unit: '%',
    range: [15, 30],
    lowAdvice: 'You float too rarely in position. Call more c-bets with backdoor equity and plan to take the pot later.',
    highAdvice: 'You float too many flop c-bets. Fold more weak hands without a plan for the turn.',
  },
  {
    id: 'foldToFCbetHu',
    label: 'Fold to F Cbet (HU)',
    aliases: ['Fold to F Cbet (HU)', 'Fold to F CBet (HU)', 'Fold to Flop C-Bet HU'],
    category: 'postflop',
    unit: '%',
    range: [42, 56],
    lowAdvice: 'You call flop c-bets too wide. Fold more weak hands with no backdoor equity.',
    highAdvice: 'You fold too much to flop c-bets — one bet wins your stack. Float more with position and equity.',
  },
  {
    id: 'foldToFCbet3B',
    label: 'Fold to F CBet (3B)',
    aliases: ['Fold to F CBet (3B)', 'Fold to F Cbet (3B)', 'Fold to Flop CBet 3Bet Pot'],
    category: 'postflop',
    unit: '%',
    range: [48, 65],
    lowAdvice: 'You defend too wide vs c-bets in 3-bet pots. Fold more air and weak pairs.',
    highAdvice: 'You fold too much to c-bets in 3-bet pots — opponents can barrel you off equity.',
  },
  {
    id: 'foldToFFloatHu',
    label: 'Fold to F Float HU',
    aliases: ['Fold to F Float HU', 'Fold to Flop Float HU'],
    category: 'postflop',
    unit: '%',
    range: [58, 78],
    lowAdvice: 'You fight floats too often — check-raise or barrel more when floated.',
    highAdvice: 'You fold too much when floated. Bet the turn more with your strong hands and bluffs.',
  },
  {
    id: 'cbetFAndFoldHu',
    label: 'CBet F & Fold (HU)',
    aliases: ['CBet F & Fold (HU)', 'CBet F and Fold HU'],
    category: 'postflop',
    unit: '%',
    range: [42, 60],
    lowAdvice: 'You give up too rarely after c-betting — fine if you barrel well.',
    highAdvice: 'You c-bet and fold too often. Either check more flops or defend more vs raises.',
  },
  {
    id: 'raiseFCbetHu',
    label: 'Raise F CBet (HU)',
    aliases: ['Raise F CBet (HU)', 'Raise F Cbet (HU)', 'Raise Flop CBet HU'],
    category: 'postflop',
    unit: '%',
    range: [7, 14],
    lowAdvice: 'You raise flop c-bets too rarely. Add check-raises with strong hands and draws.',
    highAdvice: 'You raise flop c-bets too often. Tighten your raising range to value and strong draws.',
  },
  {
    id: 'xrFlopHu',
    label: 'XR Flop HU',
    aliases: ['XR Flop HU', 'Check-Raise Flop HU'],
    category: 'postflop',
    unit: '%',
    range: [5, 12],
    lowAdvice: 'You check-raise the flop too rarely OOP. Add XR with strong hands and combo draws.',
    highAdvice: 'You check-raise the flop very often. Balance with more checks and calls.',
  },
  {
    id: 'raiseFCbet3B',
    label: 'Raise F CBet (3B)',
    aliases: ['Raise F CBet (3B)', 'Raise F Cbet (3B)'],
    category: 'postflop',
    unit: '%',
    range: [5, 12],
    lowAdvice: 'You rarely raise c-bets in 3-bet pots. Add XR/raises with top pair+ and strong draws.',
    highAdvice: 'You raise flop c-bets too often in 3-bet pots. Narrow to nutted hands and best draws.',
  },
  {
    id: 'donkTHu',
    label: 'Donk T (HU)',
    aliases: ['Donk T (HU)', 'Donk Turn HU'],
    category: 'postflop',
    unit: '%',
    range: [2, 12],
    lowAdvice: 'Low donk-bet turn frequency is normal.',
    highAdvice: 'You donk the turn too often. Leading turn is usually a leak — prefer check-call or check-raise.',
  },
  {
    id: 'cbetTHu',
    label: 'CBet T (HU)',
    aliases: ['CBet T (HU)', 'C-Bet Turn HU', 'CBet Turn HU'],
    category: 'postflop',
    unit: '%',
    range: [38, 52],
    lowAdvice: 'You give up on the turn too often after c-betting. Double barrel more on good turn cards.',
    highAdvice: 'You barrel the turn very often. Ensure second barrels land on cards that favor your range.',
  },
  {
    id: 'floatT',
    label: 'Float T',
    aliases: ['Float T', 'Float Turn'],
    category: 'postflop',
    unit: '%',
    range: [12, 26],
    lowAdvice: 'You float the turn too rarely. Call more with position when you have equity to realize.',
    highAdvice: 'You float the turn too often. Fold more marginal hands without river plan.',
  },
  {
    id: 'probeTHu',
    label: 'Probe T (HU)',
    aliases: ['Probe T (HU)', 'Probe Turn HU'],
    category: 'postflop',
    unit: '%',
    range: [22, 40],
    lowAdvice: 'You probe the turn too rarely after checking flop. Bet more when checked to and you have equity.',
    highAdvice: 'You probe the turn too often. Be selective on cards that favor your range.',
  },
  {
    id: 'probeTHuAndBetR',
    label: 'Probe T & Bet R',
    aliases: ['Probe T HU & Bet R', 'Probe T HU and Bet River'],
    category: 'postflop',
    unit: '%',
    range: [30, 50],
    lowAdvice: 'You rarely follow turn probes with river bets. Add river barrels when turn card improves your range.',
    highAdvice: 'You probe turn and barrel river too often. Give up more when the river bricks.',
  },
  {
    id: 'foldToTCbet',
    label: 'Fold to T CBet',
    aliases: ['Fold to T CBet', 'Fold to Turn C-Bet', 'Fold to Turn CBet'],
    category: 'postflop',
    unit: '%',
    range: [38, 52],
    lowAdvice: 'You call turn barrels too wide. Fold more weak pairs and draws without odds.',
    highAdvice: 'You fold too much to turn barrels. Continue with more pairs and draws that beat bluffs.',
  },
  {
    id: 'foldToTPrHu',
    label: 'F to T Pr (HU)',
    aliases: ['F to T Pr (HU)', 'Fold to Turn Probe HU', 'Fold to T Probe HU'],
    category: 'postflop',
    unit: '%',
    range: [48, 65],
    lowAdvice: 'You call turn probes too wide. Fold more weak showdown value.',
    highAdvice: 'You fold too much to turn probes. Defend more with pairs and backdoor equity.',
  },
  {
    id: 'raiseTCbet',
    label: 'Raise T CBet',
    aliases: ['Raise T CBet', 'Raise Turn C-Bet'],
    category: 'postflop',
    unit: '%',
    range: [7, 16],
    lowAdvice: 'You raise turn bets too rarely. Add raises with nutted hands and strong draws.',
    highAdvice: 'You raise turn bets too often. Most turn raises should be for value or strong combo draws.',
  },
  {
    id: 'raiseTProbeHu',
    label: 'Raise T Probe (HU)',
    aliases: ['Raise T Probe (HU)', 'Raise Turn Probe HU'],
    category: 'postflop',
    unit: '%',
    range: [8, 18],
    lowAdvice: 'You rarely raise turn probes. Add raises with strong hands to punish thin probes.',
    highAdvice: 'You raise turn probes too often. Reserve raises for value and best draws.',
  },
  {
    id: 'donkR',
    label: 'Donk R',
    aliases: ['Donk R', 'Donk River'],
    category: 'postflop',
    unit: '%',
    range: [3, 15],
    lowAdvice: 'Low donk-river frequency is normal.',
    highAdvice: 'You donk the river too often. Leading river is usually a leak unless you block-callers.',
  },
  {
    id: 'cbetR',
    label: 'CBet R',
    aliases: ['CBet R', 'C-Bet River', 'CBet River'],
    category: 'postflop',
    unit: '%',
    range: [45, 65],
    lowAdvice: 'You value-bet and bluff the river too rarely. Bet more when you have clear value or blockers.',
    highAdvice: 'You bet the river too often. Check more marginal hands and give up on missed bluffs.',
  },
  {
    id: 'foldToRCbet',
    label: 'Fold to R CBet',
    aliases: ['Fold to R CBet', 'Fold to River C-Bet', 'Fold to River CBet'],
    category: 'postflop',
    unit: '%',
    range: [48, 65],
    lowAdvice: 'You call river bets too light — a calling-station leak. Fold more marginal bluff-catchers.',
    highAdvice: 'You fold too much to river bets. Call down lighter vs aggressive opponents with blockers.',
  },
  {
    id: 'vpip',
    label: 'VPIP',
    aliases: ['VP$IP', 'VPIP'],
    category: 'preflop',
    unit: '%',
    range: [18, 24],
    lowAdvice: 'You are playing too tight preflop. Add suited connectors, suited aces, and late-position opens.',
    highAdvice: 'You are playing too many hands. Tighten up in early position and stop calling with weak offsuit hands.',
  },
]
